// Neat procedural-texture presets — the 4 presets that use enableProceduralTexture: true.
// Ported verbatim from @firecms/neat (MIT + Commons Clause), https://github.com/FireCMSco/neat
// These extend the 19 non-procedural presets shipped in Phase 11D-1.
//
// The texture* / procedural* fields are NEW in the 11D-2 ShaderConfig (added this milestone).
// All values are exact; the texture* fields are used raw (Neat applies no setter scaling to them).

import type { ShaderPreset } from './shader-presets-data';

export const NEAT_PROCEDURAL_PRESETS: ShaderPreset[] = [
  {
    id: 'funky',
    name: 'Funky',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#FB5066', enabled: true },
        { color: '#36CCD6', enabled: true },
        { color: '#FFC600', enabled: true },
        { color: '#8B6AE6', enabled: true },
        { color: '#2E0EC7', enabled: true },
        { color: '#FF9A9E', enabled: true },
      ],
      speed: 1,
      waveAmplitude: 10,
      waveFrequencyX: 3,
      waveFrequencyY: 5,
      horizontalPressure: 3,
      verticalPressure: 3,
      colorBlending: 3,
      shadows: 2,
      highlights: 6,
      colorBrightness: 1.05,
      colorSaturation: 1,
      grainScale: 0,
      grainIntensity: 0,
      grainSpeed: 2.4,
      grainSparsity: 0,
      flowEnabled: true,
      flowDistortionA: 0.4,
      flowDistortionB: 2.6,
      flowScale: 1.9,
      flowEase: 0.94,
      yOffset: 10333,
      yOffsetWaveMultiplier: 7.2,
      yOffsetColorMultiplier: 6.8,
      yOffsetFlowMultiplier: 7.7,
      mouseDistortionStrength: 0.1,
      mouseDistortionRadius: 0.25,
      backgroundColor: '#003FFF',
      resolution: 0.7,
      enableProceduralTexture: true,
      textureVoidLikelihood: 0.59,
      textureVoidWidthMin: 120,
      textureVoidWidthMax: 330,
      textureBandDensity: 0.1,
      textureColorBlending: 0,
      textureSeed: 478,
      textureEase: 0.86,
      proceduralBackgroundColor: '#003FFF',
      textureShapeTriangles: 20,
      textureShapeCircles: 15,
      textureShapeBars: 15,
      textureShapeSquiggles: 10,
    },
  },
  {
    id: 'fluid',
    name: 'Fluid',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#899D99', enabled: true },
        { color: '#5f2727', enabled: true },
        { color: '#373c38', enabled: true },
        { color: '#0099bb', enabled: true },
        { color: '#303B42', enabled: true },
        { color: '#2E7075', enabled: true },
      ],
      speed: 1.5,
      waveAmplitude: 0,
      waveFrequencyX: 4,
      waveFrequencyY: 5,
      horizontalPressure: 5,
      verticalPressure: 4,
      colorBlending: 3,
      shadows: 4,
      highlights: 4,
      colorBrightness: 1,
      colorSaturation: 0,
      grainScale: 2,
      grainIntensity: 0.575,
      grainSpeed: 0.1,
      grainSparsity: 0,
      flowEnabled: true,
      flowDistortionA: 3.7,
      flowDistortionB: 1.4,
      flowScale: 2.9,
      flowEase: 0.32,
      yOffset: 0,
      yOffsetWaveMultiplier: 5.5,
      yOffsetColorMultiplier: 5.2,
      yOffsetFlowMultiplier: 6.0,
      mouseDistortionStrength: 0.12,
      mouseDistortionRadius: 0.37,
      backgroundColor: '#202020',
      resolution: 0.7,
      enableProceduralTexture: true,
      textureVoidLikelihood: 0.27,
      textureVoidWidthMin: 60,
      textureVoidWidthMax: 420,
      textureBandDensity: 1.2,
      textureColorBlending: 0.06,
      textureSeed: 333,
      textureEase: 1,
      proceduralBackgroundColor: '#0E0707',
      textureShapeTriangles: 20,
      textureShapeCircles: 15,
      textureShapeBars: 15,
      textureShapeSquiggles: 10,
    },
  },
  {
    id: 'yex',
    name: 'Yex',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#FF5772', enabled: true },
        { color: '#4CB4BB', enabled: true },
        { color: '#FFC600', enabled: true },
        { color: '#8B6AE6', enabled: true },
        { color: '#2E0EC7', enabled: true },
        { color: '#FF9A9E', enabled: true },
      ],
      speed: 1,
      waveAmplitude: 7,
      waveFrequencyX: 3,
      waveFrequencyY: 2,
      horizontalPressure: 3,
      verticalPressure: 3,
      colorBlending: 4,
      shadows: 3,
      highlights: 4,
      colorBrightness: 1.05,
      colorSaturation: -2,
      grainScale: 0,
      grainIntensity: 0,
      grainSpeed: 2.4,
      grainSparsity: 0,
      flowEnabled: true,
      flowDistortionA: 1.2,
      flowDistortionB: 2.4,
      flowScale: 1.5,
      flowEase: 0.41,
      yOffset: 162,
      yOffsetWaveMultiplier: 3.8,
      yOffsetColorMultiplier: 4.2,
      yOffsetFlowMultiplier: 5.5,
      mouseDistortionStrength: 0.38,
      mouseDistortionRadius: 0.05,
      backgroundColor: '#4A3805',
      resolution: 0.7,
      enableProceduralTexture: true,
      textureVoidLikelihood: 0.06,
      textureVoidWidthMin: 10,
      textureVoidWidthMax: 500,
      textureBandDensity: 0.8,
      textureColorBlending: 0.06,
      textureSeed: 333,
      textureEase: 0.42,
      proceduralBackgroundColor: '#FFED00',
      textureShapeTriangles: 20,
      textureShapeCircles: 15,
      textureShapeBars: 15,
      textureShapeSquiggles: 10,
    },
  },
  {
    id: 'virus',
    name: 'Virus',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#FB5066', enabled: true },
        { color: '#00EFFF', enabled: true },
        { color: '#0F0635', enabled: true },
        { color: '#8B6AE6', enabled: true },
        { color: '#0F0635', enabled: true },
        { color: '#FBFF00', enabled: true },
      ],
      speed: 2,
      waveAmplitude: 2,
      waveFrequencyX: 1,
      waveFrequencyY: 0,
      horizontalPressure: 3,
      verticalPressure: 3,
      colorBlending: 3,
      shadows: 2,
      highlights: 6,
      colorBrightness: 1.05,
      colorSaturation: 3,
      grainScale: 5,
      grainIntensity: 0.25,
      grainSpeed: 2.4,
      grainSparsity: 0.1,
      flowEnabled: true,
      flowDistortionA: 1.7,
      flowDistortionB: 2.2,
      flowScale: 2.6,
      flowEase: 0.15,
      yOffset: 17472.722391344607,
      yOffsetWaveMultiplier: 9.5,
      yOffsetColorMultiplier: 13.7,
      yOffsetFlowMultiplier: 9.9,
      mouseDistortionStrength: 0.89,
      mouseDistortionRadius: 0.4,
      backgroundColor: '#003FFF',
      resolution: 0.7,
      enableProceduralTexture: true,
      textureVoidLikelihood: 0.44,
      textureVoidWidthMin: 140,
      textureVoidWidthMax: 150,
      textureBandDensity: 1.9,
      textureColorBlending: 0.12,
      textureSeed: 333,
      textureEase: 0.3,
      proceduralBackgroundColor: '#D0DBFB',
      textureShapeTriangles: 46,
      textureShapeCircles: 15,
      textureShapeBars: 15,
      textureShapeSquiggles: 10,
    },
  },
];
