// Neat preset library — 19 non-procedural presets
// Ported verbatim from @firecms/neat (MIT + Commons Clause), https://github.com/FireCMSco/neat
// The 4 procedural-texture presets (Funky, Fluid, Yex, Virus) are excluded — they arrive in Phase 11D-2.
//
// Each entry maps to ShaderConfig. Fields a preset omits should be filled from DEFAULT_CONFIG.
// Neat's source includes extra fields not in our 11D-1 ShaderConfig (wireframe, backgroundAlpha,
// mouseDecayRate, mouseDarken, textureEase, all texture*/procedural fields) — those are dropped here.

import type { ShaderConfig } from './shader-types';

export interface ShaderPreset {
  id: string;
  name: string;
  shaderId: 'neat-gradient';
  config: Partial<ShaderConfig>;
}

export const NEAT_PRESETS: ShaderPreset[] = [
  {
    id: 'neat',
    name: 'Neat',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#FF5772', enabled: true },
        { color: '#4CB4BB', enabled: true },
        { color: '#FFC600', enabled: true },
        { color: '#8B6AE6', enabled: true },
        { color: '#2E0EC7', enabled: true },
        { color: '#FF9A9E', enabled: true },
      ],
      speed: 2.5,
      waveAmplitude: 5,
      waveFrequencyX: 2,
      waveFrequencyY: 3,
      horizontalPressure: 3,
      verticalPressure: 4,
      colorBlending: 8,
      shadows: 1,
      highlights: 5,
      colorBrightness: 1,
      colorSaturation: 7,
      grainScale: 0,
      grainIntensity: 0,
      grainSpeed: 1,
      grainSparsity: 0.0,
      flowEnabled: true,
      yOffsetWaveMultiplier: 4,
      yOffsetColorMultiplier: 4,
      yOffsetFlowMultiplier: 4,
      backgroundColor: '#003FFF',
      resolution: 1,
    },
  },
  {
    id: 'stripe',
    name: 'Stripe',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#FD113F', enabled: true },
        { color: '#90E0FF', enabled: true },
        { color: '#FFC858', enabled: true },
        { color: '#753BFF', enabled: true },
        { color: '#f5e1e5', enabled: false },
        { color: '#B8D4E6', enabled: false },
      ],
      speed: 2,
      waveAmplitude: 10,
      waveFrequencyX: 1,
      waveFrequencyY: 2,
      horizontalPressure: 5,
      verticalPressure: 6,
      colorBlending: 9,
      shadows: 0,
      highlights: 7,
      colorBrightness: 1.05,
      colorSaturation: 0,
      grainScale: 0,
      grainIntensity: 0,
      grainSpeed: 0,
      flowEnabled: false,
      yOffsetWaveMultiplier: 6.5,
      yOffsetColorMultiplier: 5,
      yOffsetFlowMultiplier: 3,
      mouseDistortionStrength: 0.1,
      mouseDistortionRadius: 0.25,
      backgroundColor: '#003FFF',
      resolution: 1,
    },
  },
  {
    id: 'firecms',
    name: 'FireCMS',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#FF5373', enabled: true },
        { color: '#FFC858', enabled: true },
        { color: '#17E7FF', enabled: true },
        { color: '#6D3BFF', enabled: true },
        { color: '#f5e1e5', enabled: false },
        { color: '#A8E6CF', enabled: false },
      ],
      speed: 2,
      waveAmplitude: 5,
      waveFrequencyX: 2,
      waveFrequencyY: 2,
      horizontalPressure: 2,
      verticalPressure: 5,
      colorBlending: 6,
      shadows: 10,
      highlights: 8,
      colorBrightness: 1,
      colorSaturation: 10,
      grainScale: 0,
      grainIntensity: 0,
      grainSpeed: 0,
      grainSparsity: 0,
      flowEnabled: false,
      yOffsetWaveMultiplier: 3.5,
      yOffsetColorMultiplier: 3.5,
      yOffsetFlowMultiplier: 3.5,
      mouseDistortionStrength: 0.12,
      mouseDistortionRadius: 0.25,
      backgroundColor: '#003FFF',
      resolution: 0.95,
    },
  },
  {
    id: 'flame',
    name: 'Flame',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#FF0069', enabled: true },
        { color: '#00EAFF', enabled: true },
        { color: '#FFB700', enabled: true },
        { color: '#B26AE6', enabled: true },
        { color: '#2E0EC7', enabled: true },
      ],
      speed: 4,
      waveAmplitude: 10,
      waveFrequencyX: 10,
      waveFrequencyY: 0,
      horizontalPressure: 3,
      verticalPressure: 4,
      colorBlending: 9,
      shadows: 5,
      highlights: 10,
      colorBrightness: 1,
      colorSaturation: 2,
      grainScale: 2,
      grainIntensity: 0.05,
      grainSpeed: 1,
      grainSparsity: 0,
      flowEnabled: true,
      yOffsetWaveMultiplier: 8.5,
      yOffsetColorMultiplier: 7.8,
      yOffsetFlowMultiplier: 9.0,
      backgroundColor: '#003FFF',
      resolution: 0.5,
    },
  },
  {
    id: 'bloom',
    name: 'Bloom',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#FF0A39', enabled: true },
        { color: '#FFC858', enabled: true },
        { color: '#17E7FF', enabled: true },
        { color: '#4A21FF', enabled: true },
        { color: '#f5e1e5', enabled: false },
      ],
      speed: 4,
      waveAmplitude: 0,
      waveFrequencyX: 0,
      waveFrequencyY: 0,
      horizontalPressure: 6,
      verticalPressure: 6,
      colorBlending: 6,
      shadows: 0,
      highlights: 0,
      colorBrightness: 1.95,
      colorSaturation: 10,
      grainScale: 0,
      grainIntensity: 0,
      grainSpeed: 0,
      grainSparsity: 0,
      flowEnabled: true,
      yOffsetWaveMultiplier: 3.2,
      yOffsetColorMultiplier: 3.5,
      yOffsetFlowMultiplier: 4.0,
      backgroundColor: '#003FFF',
      resolution: 1,
    },
  },
  {
    id: 'sands',
    name: 'Sands',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#AD6C1F', enabled: true },
        { color: '#4CB4BB', enabled: true },
        { color: '#FFC600', enabled: true },
        { color: '#835C51', enabled: true },
        { color: '#836803', enabled: true },
      ],
      speed: 1,
      waveAmplitude: 8,
      waveFrequencyX: 2,
      waveFrequencyY: 4,
      horizontalPressure: 3,
      verticalPressure: 10,
      colorBlending: 8,
      shadows: 1,
      highlights: 5,
      colorBrightness: 1,
      colorSaturation: 7,
      grainScale: 3,
      grainIntensity: 0.3,
      grainSpeed: 5,
      grainSparsity: 0,
      flowEnabled: false,
      yOffsetWaveMultiplier: 2.8,
      yOffsetColorMultiplier: 3.0,
      yOffsetFlowMultiplier: 2.5,
      mouseDistortionStrength: 0.08,
      mouseDistortionRadius: 0.25,
      backgroundColor: '#003FFF',
      resolution: 1,
    },
  },
  {
    id: 'monterey',
    name: 'Monterey',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#130437', enabled: true },
        { color: '#B34BD0', enabled: true },
        { color: '#210751', enabled: true },
        { color: '#3511A5', enabled: true },
        { color: '#8F3E8D', enabled: false },
        { color: '#FF9A9E', enabled: false },
      ],
      speed: 4,
      waveAmplitude: 0,
      waveFrequencyX: 0,
      waveFrequencyY: 0,
      horizontalPressure: 7,
      verticalPressure: 3,
      colorBlending: 9,
      shadows: 4,
      highlights: 0,
      colorBrightness: 1.95,
      colorSaturation: 2,
      grainScale: 6,
      grainIntensity: 0.125,
      grainSpeed: 0,
      grainSparsity: 0,
      flowEnabled: true,
      flowDistortionA: 0.4,
      flowDistortionB: 10,
      flowScale: 3.3,
      flowEase: 0.37,
      yOffset: 150,
      yOffsetWaveMultiplier: 4.5,
      yOffsetColorMultiplier: 4.8,
      yOffsetFlowMultiplier: 5.2,
      mouseDistortionStrength: 0.15,
      backgroundColor: '#003FFF',
      resolution: 1.15,
    },
  },
  {
    id: 'alejandra',
    name: 'Alejandra',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#FF5373', enabled: true },
        { color: '#17E7FF', enabled: true },
        { color: '#FFC858', enabled: true },
        { color: '#6D3BFF', enabled: true },
        { color: '#f5e1e5', enabled: false },
      ],
      speed: 6,
      waveAmplitude: 8,
      waveFrequencyX: 1,
      waveFrequencyY: 2,
      horizontalPressure: 7,
      verticalPressure: 8,
      colorBlending: 10,
      shadows: 4,
      highlights: 6,
      colorBrightness: 0.95,
      colorSaturation: -8,
      grainScale: 4,
      grainIntensity: 0.25,
      grainSpeed: 1,
      grainSparsity: 0,
      flowEnabled: true,
      flowDistortionA: 1.1,
      flowDistortionB: 0.8,
      flowScale: 1.6,
      flowEase: 0.32,
      yOffset: 0,
      yOffsetWaveMultiplier: 6.2,
      yOffsetColorMultiplier: 5.8,
      yOffsetFlowMultiplier: 6.5,
      mouseDistortionStrength: 0.1,
      mouseDistortionRadius: 0.25,
      backgroundColor: '#003FFF',
      resolution: 1,
    },
  },
  {
    id: 'lemon',
    name: 'Lemon',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#F2FF00', enabled: true },
        { color: '#6B00FF', enabled: true },
        { color: '#D5ECEB', enabled: true },
        { color: '#E4E4E4', enabled: false },
        { color: '#F6FFFF', enabled: false },
      ],
      speed: 4,
      waveAmplitude: 10,
      waveFrequencyX: 1,
      waveFrequencyY: 2,
      horizontalPressure: 4,
      verticalPressure: 5,
      colorBlending: 7,
      shadows: 4,
      highlights: 7,
      colorBrightness: 1,
      colorSaturation: 0,
      grainScale: 4,
      grainIntensity: 0.2,
      grainSpeed: 2.2,
      grainSparsity: 0,
      flowEnabled: true,
      yOffsetWaveMultiplier: 5.0,
      yOffsetColorMultiplier: 4.5,
      yOffsetFlowMultiplier: 5.5,
      backgroundColor: '#00A2FF',
      resolution: 0.65,
    },
  },
  {
    id: 'glitch',
    name: 'Glitch',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#F9F27A', enabled: true },
        { color: '#FFAB00', enabled: true },
        { color: '#17E7FF', enabled: true },
        { color: '#FF0003', enabled: true },
        { color: '#671424', enabled: false },
      ],
      speed: 4,
      waveAmplitude: 10,
      waveFrequencyX: 0,
      waveFrequencyY: 6,
      horizontalPressure: 4,
      verticalPressure: 9,
      colorBlending: 7,
      shadows: 0,
      highlights: 10,
      colorBrightness: 1,
      colorSaturation: 7,
      grainScale: 0,
      grainIntensity: 0,
      grainSpeed: 0,
      grainSparsity: 0,
      flowEnabled: true,
      yOffsetWaveMultiplier: 11.5,
      yOffsetColorMultiplier: 10.8,
      yOffsetFlowMultiplier: 12.0,
      backgroundColor: '#3600FF',
      resolution: 1.2,
    },
  },
  {
    id: 'pastel',
    name: 'Pastel',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#cdb4db', enabled: true },
        { color: '#ffc8dd', enabled: true },
        { color: '#ffafcc', enabled: true },
        { color: '#bde0fe', enabled: true },
        { color: '#a2d2ff', enabled: false },
      ],
      speed: 4,
      waveAmplitude: 6,
      waveFrequencyX: 2,
      waveFrequencyY: 4,
      horizontalPressure: 4,
      verticalPressure: 6,
      colorBlending: 5,
      shadows: 0,
      highlights: 4,
      colorBrightness: 1,
      colorSaturation: 3,
      grainScale: 0,
      grainIntensity: 0,
      grainSpeed: 0,
      grainSparsity: 0,
      flowEnabled: true,
      yOffsetWaveMultiplier: 2.5,
      yOffsetColorMultiplier: 2.8,
      yOffsetFlowMultiplier: 3.2,
      backgroundColor: '#003FFF',
      resolution: 1,
    },
  },
  {
    id: 'clouds',
    name: 'Clouds',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#FFFFFF', enabled: true },
        { color: '#EFE2CE', enabled: true },
        { color: '#D5ECEB', enabled: true },
        { color: '#E4E4E4', enabled: true },
        { color: '#F6FFFF', enabled: true },
      ],
      speed: 2,
      waveAmplitude: 2,
      waveFrequencyX: 4,
      waveFrequencyY: 3,
      horizontalPressure: 4,
      verticalPressure: 5,
      colorBlending: 7,
      shadows: 4,
      highlights: 7,
      colorBrightness: 1,
      colorSaturation: 0,
      grainScale: 100,
      grainIntensity: 0.05,
      grainSpeed: 0.3,
      grainSparsity: 0,
      flowEnabled: true,
      flowDistortionA: 0.4,
      flowDistortionB: 3,
      flowScale: 3.3,
      flowEase: 0.53,
      yOffset: 150,
      mouseDistortionStrength: 0.12,
      mouseDistortionRadius: 0.25,
      backgroundColor: '#00A2FF',
      resolution: 0.5,
    },
  },
  {
    id: 'dark-mode',
    name: 'Dark Mode',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#000000', enabled: true },
        { color: '#001129', enabled: true },
        { color: '#0F0025', enabled: true },
        { color: '#14080A', enabled: true },
        { color: '#001129', enabled: true },
      ],
      speed: 2,
      waveAmplitude: 1,
      waveFrequencyX: 3,
      waveFrequencyY: 2,
      horizontalPressure: 4,
      verticalPressure: 4,
      colorBlending: 7,
      shadows: 2,
      highlights: 2,
      colorBrightness: 1,
      colorSaturation: -1,
      grainScale: 2,
      grainIntensity: 0,
      grainSpeed: 1,
      grainSparsity: 0,
      flowEnabled: false,
      yOffset: 0,
      yOffsetWaveMultiplier: 2.2,
      yOffsetColorMultiplier: 2.5,
      yOffsetFlowMultiplier: 2.8,
      mouseDistortionStrength: 0.1,
      mouseDistortionRadius: 0.25,
      backgroundColor: '#010101',
      resolution: 0.75,
    },
  },
  {
    id: 'night-dunes',
    name: 'Night Dunes',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#554226', enabled: true },
        { color: '#03162D', enabled: true },
        { color: '#002027', enabled: true },
        { color: '#020210', enabled: true },
        { color: '#02152A', enabled: true },
        { color: '#B8D4E6', enabled: false },
      ],
      speed: 2,
      waveAmplitude: 8,
      waveFrequencyX: 1,
      waveFrequencyY: 3,
      horizontalPressure: 3,
      verticalPressure: 5,
      colorBlending: 7,
      shadows: 0,
      highlights: 2,
      colorBrightness: 1,
      colorSaturation: 6,
      grainScale: 2,
      grainIntensity: 0.175,
      grainSpeed: 1,
      grainSparsity: 0,
      flowEnabled: false,
      yOffsetWaveMultiplier: 1.8,
      yOffsetColorMultiplier: 2.0,
      yOffsetFlowMultiplier: 2.2,
      mouseDistortionStrength: 0.1,
      mouseDistortionRadius: 0.25,
      backgroundColor: '#003FFF',
      resolution: 1,
    },
  },
  {
    id: 'prussian',
    name: 'Prussian',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#0b3954', enabled: true },
        { color: '#087e8b', enabled: true },
        { color: '#bfd7ea', enabled: true },
        { color: '#ff5a5f', enabled: true },
        { color: '#c81d25', enabled: true },
        { color: '#A8E6CF', enabled: false },
      ],
      speed: 4,
      waveAmplitude: 0,
      waveFrequencyX: 0,
      waveFrequencyY: 0,
      horizontalPressure: 4,
      verticalPressure: 3,
      colorBlending: 5,
      shadows: 2,
      highlights: 7,
      colorBrightness: 1,
      colorSaturation: 8,
      grainScale: 0,
      grainIntensity: 0,
      grainSpeed: 0,
      grainSparsity: 0,
      flowEnabled: false,
      yOffsetWaveMultiplier: 1.5,
      yOffsetColorMultiplier: 1.8,
      yOffsetFlowMultiplier: 2.0,
      mouseDistortionStrength: 0.12,
      mouseDistortionRadius: 0.25,
      backgroundColor: '#FF0000',
      resolution: 0.5,
    },
  },
  {
    id: 'nighttime',
    name: 'Nighttime',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#FF3087', enabled: true },
        { color: '#1B36A6', enabled: true },
        { color: '#00D3FF', enabled: true },
        { color: '#6D3BFF', enabled: true },
        { color: '#492E52', enabled: true },
      ],
      speed: 3.5,
      waveAmplitude: 5,
      waveFrequencyX: 8,
      waveFrequencyY: 1,
      horizontalPressure: 3,
      verticalPressure: 5,
      colorBlending: 7,
      shadows: 3,
      highlights: 2,
      colorBrightness: 1,
      colorSaturation: 7,
      grainScale: 2,
      grainIntensity: 0.5,
      grainSpeed: 1,
      grainSparsity: 0,
      flowEnabled: true,
      flowDistortionA: 5,
      flowDistortionB: 7.7,
      flowScale: 2.6,
      flowEase: 0.36,
      yOffset: 110380.5,
      yOffsetWaveMultiplier: 3,
      yOffsetColorMultiplier: 3.3,
      yOffsetFlowMultiplier: 3.8,
      mouseDistortionStrength: 0.12,
      mouseDistortionRadius: 0.25,
      backgroundColor: '#003FFF',
      resolution: 1.2,
    },
  },
  {
    id: 'psychedelic',
    name: 'Psychedelic',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#00C5FF', enabled: true },
        { color: '#CEFF00', enabled: true },
        { color: '#17E7FF', enabled: true },
        { color: '#6D3BFF', enabled: true },
        { color: '#FFFB00', enabled: true },
      ],
      speed: 4,
      waveAmplitude: 10,
      waveFrequencyX: 1,
      waveFrequencyY: 2,
      horizontalPressure: 7,
      verticalPressure: 7,
      colorBlending: 9,
      shadows: 0,
      highlights: 7,
      colorBrightness: 1.05,
      colorSaturation: 0,
      grainScale: 0,
      grainIntensity: 0,
      grainSpeed: 0,
      flowEnabled: false,
      yOffsetWaveMultiplier: 13.5,
      yOffsetColorMultiplier: 12.8,
      yOffsetFlowMultiplier: 14.0,
      mouseDistortionStrength: 0.15,
      mouseDistortionRadius: 0.3,
      backgroundColor: '#003FFF',
      resolution: 1,
    },
  },
  {
    id: 'splash',
    name: 'Splash',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#ffbe0b', enabled: true },
        { color: '#fb5607', enabled: true },
        { color: '#ff006e', enabled: true },
        { color: '#8338ec', enabled: true },
        { color: '#3a86ff', enabled: true },
      ],
      speed: 4,
      waveAmplitude: 7,
      waveFrequencyX: 1,
      waveFrequencyY: 2,
      horizontalPressure: 2,
      verticalPressure: 2,
      colorBlending: 5,
      shadows: 10,
      highlights: 10,
      colorBrightness: 1,
      colorSaturation: 2,
      grainScale: 2,
      grainIntensity: 0.3,
      grainSpeed: 0,
      flowEnabled: false,
      yOffsetWaveMultiplier: 9.0,
      yOffsetColorMultiplier: 8.5,
      yOffsetFlowMultiplier: 9.5,
      mouseDistortionStrength: 0.12,
      mouseDistortionRadius: 0.25,
      backgroundColor: '#FFBE0B',
      resolution: 1,
    },
  },
  {
    id: 'oceanic',
    name: 'Oceanic',
    shaderId: 'neat-gradient',
    config: {
      colors: [
        { color: '#005F73', enabled: true },
        { color: '#0A9396', enabled: true },
        { color: '#94D2BD', enabled: true },
        { color: '#E9D8A6', enabled: true },
        { color: '#EE9B00', enabled: false },
      ],
      speed: 3,
      waveAmplitude: 8,
      waveFrequencyX: 2,
      waveFrequencyY: 2,
      horizontalPressure: 5,
      verticalPressure: 7,
      colorBlending: 10,
      shadows: 6,
      highlights: 8,
      colorBrightness: 1,
      colorSaturation: 7,
      grainScale: 3,
      grainIntensity: 0.3,
      grainSpeed: 1,
      flowEnabled: false,
      mouseDistortionStrength: 0.1,
      mouseDistortionRadius: 0.25,
      backgroundColor: '#004E64',
      resolution: 1,
    },
  },
];
